#pragma once
#include <iostream>
#include <string>
#include <fstream>
#include <vector>
#include <thread>
#include <random>
#include <istream>
#include <Windows.h>
#include "nlohmann/json.hpp"
std::vector<std::string> SETTINGS;
#include "sourse/colors.h"
Colors color;
#include "sourse/languages.h"
Texts text;
std::string FILE_DIRECTORY;
#include "sourse/numsEncryption.h"
#include "sourse/Encryptions.h"
numsEncryption ints;
Encryptions encr;